version: '3.8'
services:
  credit-application-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: credit-application-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - rabbitmq

  credit-processing-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: credit-processing-service
    ports:
      - "8090:8090"
    depends_on:
      - kafka
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: credit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
